config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"
  get "/dashboard", to: "welcome#dashboard", as: :dashboard

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :drill_groups, only: [:new, :edit, :update, :destroy, :create, :index]
  resources :drill_groups, only: [:show] do
    resources :user_drill_groups, only: [:create, :destroy]
    resources :drills
  end

  resources :user_drill_groups, only: [:index]

  resources :categories, only: [:create, :destroy, :index, :show]
  resources :answers

  resources :badges
  get "/your_badges", to: "badges#user_badges", as: :badges_of_user
  get "/leaderboard", to: "leaderboard#leaderboard", as: :leaderboard

   get '/profile', to: "profile#show", as: 'profile'
   post '/profile', to: "profile#update", as: 'edit_profile'

  resources :drills, only: [] do
    resources :answers, only: [:show, :edit, :destroy, :create]
    resources :drill_completes, only: [:create]
  end

end

app/models/drill_group.rb
class DrillGroup < ActiveRecord::Base
  has_many :drills, dependent: :destroy
  belongs_to :user

  has_many :badgings, dependent: :destroy
  has_many :badges, through: :badgings

  has_many :user_drill_groups, dependent: :destroy
  has_many :users, through: :user_drill_groups


  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  validates :name, presence: true
end

app/controllers/drill_groups_controller.rb
class DrillGroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :index]
  before_action :find_drill_group, only: [:show, :edit, :update, :destroy]


  def new
    @dg = DrillGroup.new
  end

  def create
    redirect_to drill_groups_path, alert: "Access denied." and return unless current_user.admin?
    @dg = DrillGroup.new dg_params
    @dg.user = current_user
    category_names = params[:drill_group][:category_ids].split(", ")
    category_ids = []
    category_names.each do |category|
      Category.create(name: category) unless Category.find_by_name(category)
      category_ids.push(Category.find_by_name(category).id)
    end
    @dg.category_ids = category_ids
    if @dg.save
      redirect_to drill_group_path(@dg)
    else
      redirect_to drill_groups_path
    end
  end

  def show
    @dg = DrillGroup.find params[:id]
    @drills = @dg.drills.order(created_at: :desc)
    @drill = Drill.new
    @categories = @dg.categories
  end

  def index
    @drill_groups = DrillGroup.order(updated_at: :desc)
  end

  def edit
    redirect_to drill_group_path(@dg), alert: "Access denied." and return unless can? :edit, @dg
  end

  def update
    redirect_to drill_group_path(@dg), alert: "Access denied." and return unless can? :update, @dg
    category_names = params[:drill_group][:category_ids].split(", ")
    category_ids = []
    category_names.each do |category|
      Category.create(name: category) unless Category.find_by_name(category)
      category_ids.push(Category.find_by_name(category).id)
    end
    if @dg.update dg_params
      @dg.category_ids = category_ids
      @dg.save
      redirect_to(drill_group_path(@dg))
    else
      render :edit
    end
  end

  def destroy
    redirect_to drill_group_path(@dg), alert: "Access denied." and return unless can? :destroy, @dg
    @dg.destroy
    flash[:notice] = "Drill group deleted successfully"
    redirect_to drill_groups_path
  end

  private

  def dg_params
    params.require(:drill_group).permit(:name, :description, :level, {badge_ids: []}, {category_ids: []})
  end

  def find_drill_group
    @dg = DrillGroup.find params[:id]
  end

end

app/helpers/drill_groups_helper.rb
module DrillGroupsHelper
end

app/views/drill_groups/_form.html.erb
<div class="col-md-8 col-md-offset-2">
<%= simple_form_for @dg do |f| %>
  <%= f.input :name, hint: "Requires a name" %>
  <%= f.input :description%>

  <div class="badge-checkbox">
  <%= f.association :badges, :as => :check_boxes, item_wrapper_tag: :div, item_wrapper_class: "badges", :collection => Badge.order(:name),
  :label => false, :inline_label => false, :label_method => lambda { |b|  image_tag(b.image)  } %>
  </div>

<div class="buffer"></div>
  <%= f.input :level,
          :collection => [[0, "Beginner"], [1, "Intermediate"], [2, "Advanced"]],
          :label_method => :last,
          :value_method => :first,
          :as => :radio_buttons,
          :item_wrapper_class => 'inline',
          :checked => true%>
  <div class="buffer"></div>
    <%= f.association :categories,
          as: :search, data:
          {autcomplete_source: categories_path} %>
  <div class="buffer"></div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>
</div>

app/views/drill_groups/edit.html.erb
<h1 class="page-header">Editing Drill Group</h1>

<%= render "form" %>

app/views/drill_groups/index.html.erb
<h1 class="page-header">All Drill Groups</h1>


<div class="col-md-8 col-md-offset-2">
  <% @drill_groups.each do |dg| %>
    <% if dg.drills.any? || current_user.admin %>
      <div class="well clickable_html">
          <%= dg.name %>
          <%= link_to "Show", drill_group_path(dg), class: "btn btn-primary btn-sm pull-right" %>
          <%= link_to "Add To My Drills", drill_group_user_drill_groups_path(dg), class: "btn btn-info btn-sm pull-right", method: :post %>
          <div class="pull-right">
            score: <%= current_user.get_drill_group_score(dg)%> %
          </div>
      </div>
    <% end %>
  <% end %>
</div>


<!-- <% if user_signed_in? && current_user.admin?%>
  <p class="navbar-text navbar-right"><%#= link_to "Create Drill Group", new_drill_group_path %> </p>
  <p class="navbar-text navbar-right"><%#= link_to "Badges Created by You", root_path  %></p>
<% elsif user_signed_in? && !current_user.admin? %>
  <p class="navbar-text navbar-right">Signed in as <%= current_user.full_name %></p>
  <p class="navbar-text navbar-right"><%#= link_to "Your Badges", badges_of_user_path  %></p>
<% end %> -->
    <!-- <li> <%#= link_to("Profile", profile_path) %></li> -->
<!-- <p class="navbar-text navbar-right"><%#= link_to "Profile", root_path %> </p>
<p class="navbar-text navbar-right"><%#= link_to "Categories", categories_path  %></p>
<p class="navbar-text navbar-right"><%#= link_to "Leaderboard", leaderboard_path  %></p> -->

app/views/drill_groups/new.html.erb
<h1 id="title">Drill Group</h1>
    <%= render "form" %>

app/views/drill_groups/show.html.erb
<div class="col-md-2"></div>
<div class="col-md-8">
  <h1 id="title"><%= @dg.name %></h1>
  <p style="font-size: 40px;" id="title">Description:</p>
  <div id="description" class="well">
    <%= @dg.description %>
  </div>
  <% level = "" %>
  <% if @dg.level == 0 %>
    <% level = "Beginner" %>
  <% elsif @dg.level == 1 %>
    <% level = "Intermediate" %>
  <% else %>
    <% level = "Advanced" %>
  <% end %>
  <%= level %>

  <div class="buffer" style="height: 40px;">

  <div>
    <% if @categories.any? %>
      <p>This drill group belongs to <%= pluralize(@categories.count, "category") %>:
      <% @categories.each do |category| %>
        <%= category.name %>
      <% end %>
      </p>
    <% else %>
      <p>This drill group doesn't belong to any categories</p>
    <% end %>
  </div>

  <div>
  <% if @dg.badges.any? %>
    <br>
    <p>Badges you can win on completion:</p>
    <% @dg.badges.each do |badge| %>
      <!-- <div class="label label-default"> -->
      <div class="badges">
        <div> <%= image_tag(badge.image_url(:small)) %> </div>
      </div>
    <% end %>
    <br><br>
  <% end %>
  </div>


  <% if user_signed_in? && current_user.admin %>
    <%= link_to "Edit", edit_drill_group_path(@dg), class: "btn btn-info btn-sm" %>
    <%= link_to "Delete", drill_group_path(@dg), {method: :delete, class: "btn btn-danger btn-sm", data: {confirm: "Are you sure you want to delete this drill group?"}}%>
    <h2 id="add_drill_heading">Add a Drill</h2>

    <%= render 'drills/form' %>
  <% end %>

  <% if @drills.any? %>
    <h2>Drills</h2>
    <div id="drills">
      <% @drills.each do |drill| %>
        <div class="well" id="<%= dom_id(drill) %>">
        <%= drill.name %>
        <%= drill.description %>
        <%= link_to "Show", drill_group_drill_path(@dg, drill), class: "btn btn-primary btn-sm pull-right" %>
        </div>

      <% end %>
    </div>
  <% end %>

  <div style="height: 80px;" class="buffer"></div>
</div>
<div class="col-md-2"></div>