config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"
  get "/dashboard", to: "welcome#dashboard", as: :dashboard

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :drill_groups, only: [:new, :edit, :update, :destroy, :create, :index]
  resources :drill_groups, only: [:show] do
    resources :user_drill_groups, only: [:create, :destroy]
    resources :drills
  end

  resources :user_drill_groups, only: [:index]

  resources :categories, only: [:create, :destroy, :index, :show]
  resources :answers

  resources :badges
  get "/your_badges", to: "badges#user_badges", as: :badges_of_user
  get "/leaderboard", to: "leaderboard#leaderboard", as: :leaderboard

   get '/profile', to: "profile#show", as: 'profile'
   post '/profile', to: "profile#update", as: 'edit_profile'

  resources :drills, only: [] do
    resources :answers, only: [:show, :edit, :destroy, :create]
    resources :drill_completes, only: [:create]
  end

end

app/models/badge.rb
class Badge < ActiveRecord::Base

  has_many :badgings, dependent: :destroy
  has_many :drill_groups, through: :badgings

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  mount_uploader :image, BadgeImgUploader

  validates :name, presence: true, uniqueness: true

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController

    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    before_action :find_badge, only: [:show, :edit, :update, :destroy]

    # create_table "badges", force: :cascade do |t|
    #   t.datetime "created_at", null: false
    #   t.datetime "updated_at", null: false
    #   t.string   "name"
      # image
    # end

    def new
      @badge = Badge.new
    end

    def user_badges
      @badges = current_user.badges
    end

    def index
      @badges = Badge.all
    end

    def create
      @badge = Badge.new badge_params
      if @badge.save
        redirect_to badge_path @badge
      else
        render :new
      end
    end

    def destroy
      @badge.destroy
      redirect_to badges_path, notice: "Badge deleted."
    end

    def show
    end

    def edit

    end

    def update
      if @badge.update badge_params
        redirect_to badge_path @badge
      else
        render :new
      end
    end

    private

      def badge_params
        params.require(:badge).permit([:name, :image])
      end

      def find_badge
        @badge = Badge.find(params[:id])
      end


end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/_form.html.erb
<%= simple_form_for @badge, html: {multipart: true} do |f| %>
<%= f.input :name, placeholder: "badge name..." %>
<%= f.input :image %>
<%= f.submit %>
<% end %>

app/views/badges/edit.html.erb
<h1>Edit Badge</h1>
<%= render "form" %>

app/views/badges/index.html.erb
<h1>Badges</h1>

<div>
<%= link_to "New", new_badge_path, class: "btn btn-default" %>
</div>
<hr>

<% @badges.each do |b| %>
  <%= link_to b.name, badge_path(b) %>&nbsp&nbsp&nbsp
  <% if b.image.present? %>
    <%= image_tag b.image.url(:small) %>
  <% end %>
  <%= link_to "Show", badge_path(b), class: "btn btn-default pull-right" %>
  <%= link_to "Edit", edit_badge_path(b), class: "btn btn-default pull-right" %>
  <%= link_to "Delete", badge_path(b), method: :delete, class: "btn btn-default pull-right" %>
  <hr>
<% end %>

app/views/badges/new.html.erb
<h1>Create a New Badge</h1>
<%= render "form" %>

app/views/badges/show.html.erb
<h1>Badge: <%= @badge.name %></h1>
<div class="col-md-4">

</div>
<div class="col-md-4">
  <% if @badge.image.present? %>
    <%= image_tag @badge.image.url(:small) %>
  <% end %>

</div>
<div class="col-md-4">

</div>

app/views/badges/user_badges.html.erb
<h1>Look at all those badges you have! Go get more, tiger!</h1>

<% @badges.each do |b|%>
  <%= b.name %>
<% end %>