config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"
  get "/dashboard", to: "welcome#dashboard", as: :dashboard

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :drill_groups, only: [:new, :edit, :update, :destroy, :create, :index]
  resources :drill_groups, only: [:show] do
    resources :user_drill_groups, only: [:create, :destroy]
    resources :drills
  end

  resources :user_drill_groups, only: [:index]

  resources :categories, only: [:create, :destroy, :index, :show]
  resources :answers

  resources :badges
  get "/your_badges", to: "badges#user_badges", as: :badges_of_user
  get "/leaderboard", to: "leaderboard#leaderboard", as: :leaderboard

   get '/profile', to: "profile#show", as: 'profile'
   post '/profile', to: "profile#update", as: 'edit_profile'

  resources :drills, only: [] do
    resources :answers, only: [:show, :edit, :destroy, :create]
    resources :drill_completes, only: [:create]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, DrillGroup do |dg|
      user.admin
    end

    can :manage, Drill do |d|
      user.admin
    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :drill
  belongs_to :user

  validates :description, presence: true
  validates :type_of, presence: true
end

app/models/badge.rb
class Badge < ActiveRecord::Base

  has_many :badgings, dependent: :destroy
  has_many :drill_groups, through: :badgings

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  mount_uploader :image, BadgeImgUploader

  validates :name, presence: true, uniqueness: true

end

app/models/badging.rb
class Badging < ActiveRecord::Base
  belongs_to :drill_group
  belongs_to :badge
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :drill_group
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :categorizations, dependent: :destroy
  has_many :drill_groups, through: :categorizations
end

app/models/drill.rb
class Drill < ActiveRecord::Base

  has_many :answers, dependent: :destroy
  has_many :drill_completes, dependent: :destroy
  has_many :driller_users, through: :drill_completes, source: :user

  belongs_to :drill_group
  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
  validates :points, numericality: {greater_than_or_equal_to: 0}
end

app/models/drill_complete.rb
class DrillComplete < ActiveRecord::Base
  belongs_to :user
  belongs_to :drill

  validates :drill_id, uniqueness: {scope: :user_id}

  attr_accessor :new_answer
end

app/models/drill_group.rb
class DrillGroup < ActiveRecord::Base
  has_many :drills, dependent: :destroy
  belongs_to :user

  has_many :badgings, dependent: :destroy
  has_many :badges, through: :badgings

  has_many :user_drill_groups, dependent: :destroy
  has_many :users, through: :user_drill_groups


  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :profile_pic, ProfilePicUploader

  has_many :drill_completes, dependent: :nullify
  has_many :drills, through: :drill_completes

  has_many :user_badges, dependent: :nullify
  has_many :badges, through: :user_badges

  has_many :drill_groups, dependent: :nullify
  has_many :drills, dependent: :nullify

  has_many :user_drill_groups, dependent: :nullify
  has_many :drill_groups, through: :user_drill_groups



  def full_name
    "#{first_name} #{last_name}"
  end

  # needs to be calculated in real time since more drills can be added.
  # this is the percentage score
  def get_drill_group_score(drill_group)
    return 100 if drill_group.drills.count == 0

    drills_complete = 0
    drill_group.drills.each do |drill|
      if drill_completes.exists?(drill_id: drill)
        drills_complete += 1
      end
    end
    (drills_complete.to_f / drill_group.drills.count * 100).round(0)
  end



end

app/models/user_badge.rb
class UserBadge < ActiveRecord::Base
  belongs_to :user
  belongs_to :badge
end

app/models/user_drill_group.rb
class UserDrillGroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :drill_group

  validates :drill_group_id, uniqueness: {scope: :user_id}

  #def contains?()
end

app/controllers/user_drill_groups_controller.rb
class UserDrillGroupsController < ApplicationController

  def create
    @udg   = current_user.user_drill_groups.new
    @dg     = DrillGroup.find params[:drill_group_id]
    @udg.drill_group = @dg
    respond_to do |format|
      if @udg.save
        format.html { redirect_to user_drill_groups_path, notice: "Added to My Drills!" }
        format.js { render :create_success }
      else
        format.html { redirect_to user_drill_groups_path, alert: "Already Added!" }
      end
    end
  end


  def destroy
    @dg = DrillGroup.find params[:drill_group_id]
    @udg      = current_user.user_drill_groups.find params[:id]
    @udg.destroy
    respond_to do |format|
      format.html { redirect_to user_drill_groups_path, notice: "Removed from My Drills!" }
      format.js { render }
    end
  end

  def index
    @all_drill_groups = DrillGroup.all
    @user_drill_groups = current_user.user_drill_groups
    @dg = DrillGroup.new
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/drill_groups_helper.rb
module DrillGroupsHelper
end

app/helpers/drills_helper.rb
module DrillsHelper
end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/user_drill_groups_helper.rb
module UserDrillGroupsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/user_drill_groups/index.html.erb
<div class="container col-md-2"></div>
<div class="container col-md-8">
  <h1 id="title">Drill Groups</h1>

  <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a id="title" href="#home" aria-controls="home" role="tab" data-toggle="tab">Mine</a></li>
      <li role="presentation"><a id="title" href="#profile" aria-controls="profile" role="tab" data-toggle="tab">All</a></li>
      <% if current_user.admin? %>
        <li role="presentation"><a id="title" href="#create-drill-group" aria-controls="create-drill-group" role="tab" data-toggle="tab">Create a Drill Group</a></li>
      <% end %>
  </ul>


    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="home">
          <% @user_drill_groups.each do |udg| %>
          <br>
            <div class="well clickable_html">
                <% dg = udg.drill_group %>
                <%= dg.name %>
                <%= link_to "Start", drill_group_path(dg), class: "btn btn-primary btn-sm pull-right" %>
                <%= link_to "Remove", drill_group_user_drill_group_path(dg, udg), class: "btn btn-warning btn-sm pull-right", method: :delete %>
                <br>
                <br>
                <div>
                  Score: <%= current_user.get_drill_group_score(dg)%> %
                </div>
            </div>
          <% end %>


      </div>
      <div role="tabpanel" class="tab-pane" id="profile">
          <% @all_drill_groups.each do |dg| %>
            <br>
            <div class="well">
              <%= dg.name %>
              <%= link_to "Start", drill_group_path(dg), class: "btn btn-primary btn-sm pull-right", id: "show-drill-group" %>
              <%= link_to "Add this to my Drill Groups!", drill_group_user_drill_groups_path(dg), class: "btn btn-info btn-sm pull-right margin-right", method: :post %>
              <br>
              <br>
              <div>
                Score: <%= current_user.get_drill_group_score(dg)%> %
              </div>
            </div>
            <% end %>

      </div>

      <div role="tabpanel" class="tab-pane" id="create-drill-group">

          <%= render "/drill_groups/form" %>

      </div>
    </div>

</div>
</div>
<div class="container col-md-2"></div>