config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"
  get "/dashboard", to: "welcome#dashboard", as: :dashboard

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :drill_groups, only: [:new, :edit, :update, :destroy, :create, :index]
  resources :drill_groups, only: [:show] do
    resources :user_drill_groups, only: [:create, :destroy]
    resources :drills
  end

  resources :user_drill_groups, only: [:index]

  resources :categories, only: [:create, :destroy, :index, :show]
  resources :answers

  resources :badges
  get "/your_badges", to: "badges#user_badges", as: :badges_of_user
  get "/leaderboard", to: "leaderboard#leaderboard", as: :leaderboard

   get '/profile', to: "profile#show", as: 'profile'
   post '/profile', to: "profile#update", as: 'edit_profile'

  resources :drills, only: [] do
    resources :answers, only: [:show, :edit, :destroy, :create]
    resources :drill_completes, only: [:create]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, DrillGroup do |dg|
      user.admin
    end

    can :manage, Drill do |d|
      user.admin
    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :drill
  belongs_to :user

  validates :description, presence: true
  validates :type_of, presence: true
end

app/models/badge.rb
class Badge < ActiveRecord::Base

  has_many :badgings, dependent: :destroy
  has_many :drill_groups, through: :badgings

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  mount_uploader :image, BadgeImgUploader

  validates :name, presence: true, uniqueness: true

end

app/models/badging.rb
class Badging < ActiveRecord::Base
  belongs_to :drill_group
  belongs_to :badge
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :drill_group
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :categorizations, dependent: :destroy
  has_many :drill_groups, through: :categorizations
end

app/models/drill.rb
class Drill < ActiveRecord::Base

  has_many :answers, dependent: :destroy
  has_many :drill_completes, dependent: :destroy
  has_many :driller_users, through: :drill_completes, source: :user

  belongs_to :drill_group
  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
  validates :points, numericality: {greater_than_or_equal_to: 0}
end

app/models/drill_complete.rb
class DrillComplete < ActiveRecord::Base
  belongs_to :user
  belongs_to :drill

  validates :drill_id, uniqueness: {scope: :user_id}

  attr_accessor :new_answer
end

app/models/drill_group.rb
class DrillGroup < ActiveRecord::Base
  has_many :drills, dependent: :destroy
  belongs_to :user

  has_many :badgings, dependent: :destroy
  has_many :badges, through: :badgings

  has_many :user_drill_groups, dependent: :destroy
  has_many :users, through: :user_drill_groups


  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :profile_pic, ProfilePicUploader

  has_many :drill_completes, dependent: :nullify
  has_many :drills, through: :drill_completes

  has_many :user_badges, dependent: :nullify
  has_many :badges, through: :user_badges

  has_many :drill_groups, dependent: :nullify
  has_many :drills, dependent: :nullify

  has_many :user_drill_groups, dependent: :nullify
  has_many :drill_groups, through: :user_drill_groups



  def full_name
    "#{first_name} #{last_name}"
  end

  # needs to be calculated in real time since more drills can be added.
  # this is the percentage score
  def get_drill_group_score(drill_group)
    return 100 if drill_group.drills.count == 0

    drills_complete = 0
    drill_group.drills.each do |drill|
      if drill_completes.exists?(drill_id: drill)
        drills_complete += 1
      end
    end
    (drills_complete.to_f / drill_group.drills.count * 100).round(0)
  end



end

app/models/user_badge.rb
class UserBadge < ActiveRecord::Base
  belongs_to :user
  belongs_to :badge
end

app/models/user_drill_group.rb
class UserDrillGroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :drill_group

  validates :drill_group_id, uniqueness: {scope: :user_id}

  #def contains?()
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/drills_helper.rb
module DrillsHelper
end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>" >Home</a>
      <% if user_signed_in? %>
        <a class="navbar-brand" href="<%= leaderboard_path %>">Leaderboards</a>
      <% end %>
    </div>

<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <%= link_to "Badges", badges_path, class:"nav navbar-brand" %>
          <% end %>
          <%= link_to "Drill Groups", user_drill_groups_path(current_user), class:"nav navbar-brand" %>
        <% end %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello <%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %>! <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li> <%= link_to("Log Out", destroy_user_session_path, method: :delete) %></li>
              <li> <%= link_to "Profile", profile_path %></li>
            </ul>
          </li>
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Enter<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li> <%= link_to "Sign Up", new_user_registration_path %></li>
            <li> <%= link_to "Log In", new_user_session_path %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeekendFun</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Bubblegum+Sans' rel='stylesheet' type='text/css'>
</head>
<body>
    <%= render "/layouts/nav" %>
  <div class="container">

    <% if flash[:notice]%>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert]  %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
</body>
</html>